#include <TH1.h>
#include <TH1F.h>
#include <TF1.h>
#include <TLatex.h>
#include <TList.h>
#include <TLegend.h>
#include <TCanvas.h>
#include <TAxis.h>
#include <TStyle.h>
#include <TGraph.h>

#include <iostream>

static TStyle style_test( "m_test", "test" );

void myStyle_set(){
  style_test.SetAxisColor(Color_t color = 1, Option_t* axis = "X")
  style_test.SetBarOffset( 0.5 )
  style_test.SetBarWidth( 0.5 )
  style_test.SetCanvasBorderMode( 1 )
  style_test.SetCanvasBorderSize( 1 )
  style_test.SetCanvasColor( 19 )
  style_test.SetCanvasDefH( 500 )
  style_test.SetCanvasDefW( 700 )
  style_test.SetCanvasDefX( 10 )
  style_test.SetCanvasDefY( 10 )
  style_test.SetCanvasPreferGL( kTRUE )
  style_test.SetColorModelPS( 0 )
  style_test.SetDateX( 0.01 )
  style_test.SetDateY( 0.01 )
  style_test.SetDrawBorder( 1 )
  style_test.SetEndErrorSize( 2 )
  style_test.SetErrorX( 0.5 )
  style_test.SetFitFormat(const char* format = "5.4g")
  style_test.SetFrameBorderMode( 1 )
  style_test.SetFrameBorderSize( 1 )
  style_test.SetFrameFillColor( 1 )
  style_test.SetFrameFillStyle( 0 )
  style_test.SetFrameLineColor( 1 )
  style_test.SetFrameLineStyle( 0 )
  style_test.SetFrameLineWidth( 1 )
  style_test.SetFuncColor( 1 )
  style_test.SetFuncStyle( 1 )
  style_test.SetFuncWidth( 4 )
  style_test.SetGridColor( 0 )
  style_test.SetGridStyle( 3 )
  style_test.SetGridWidth( 1 )
  style_test.SetHatchesLineWidth(Int_t l)
  style_test.SetHatchesSpacing(Double_t h)
  style_test.SetHeaderPS(const char* header)
  style_test.SetHistFillColor( 1 )
  style_test.SetHistFillStyle( 0 )
  style_test.SetHistLineColor( 1 )
  style_test.SetHistLineStyle( 0 )
  style_test.SetHistLineWidth( 1 )
  style_test.SetHistMinimumZero( kTRUE )
  style_test.SetHistTopMargin( 0.05 )
  style_test.SetIsReading( kTRUE )
  style_test.SetLabelColor(Color_t color = 1, Option_t* axis = "X")
  style_test.SetLabelFont(Style_t font = 62, Option_t* axis = "X")
  style_test.SetLabelOffset(Float_t offset = 0.005, Option_t* axis = "X")
  style_test.SetLabelSize(Float_t size = 0.04, Option_t* axis = "X")
  style_test.SetLegendBorderSize( 4 )
  style_test.SetLegoInnerR( 0.5 )
  style_test.SetLineScalePS( 3 )
  style_test.SetLineStyleString(Int_t i, const char* text)
  style_test.SetNdivisions(Int_t n = 510, Option_t* axis = "X")
  style_test.SetNumberContours( 20 )
  style_test.SetOptDate( 1 )
  style_test.SetOptFile( 1 )
  style_test.SetOptFit( 1 )
  style_test.SetOptLogx( 1 )
  style_test.SetOptLogy( 1 )
  style_test.SetOptLogz( 1 )
  style_test.SetOptStat( 1 )
  style_test.SetOptStat(Option_t* stat)
  style_test.SetOptTitle( 1 )
  style_test.SetPadBorderMode( 1 )
  style_test.SetPadBorderSize( 1 )
  style_test.SetPadBottomMargin( 0.1 )
  style_test.SetPadColor( 19 )
  style_test.SetPadGridX(Bool_t gridx)
  style_test.SetPadGridY(Bool_t gridy)
  style_test.SetPadLeftMargin( 0.1 )
  style_test.SetPadRightMargin( 0.1 )
  style_test.SetPadTickX(Int_t tickx)
  style_test.SetPadTickY(Int_t ticky)
  style_test.SetPadTopMargin( 0.1 )
  style_test.SetPaintTextFormat(const char* format = "g")
  style_test.SetPalette(Int_t ncolors = 0, Int_t* colors = 0)
  style_test.SetPaperSize(TStyle::EPaperSize size)
  style_test.SetPaperSize(Float_t xsize = 20, Float_t ysize = 26)
  style_test.SetScreenFactor( 1 )
  style_test.SetStatBorderSize( 2 )
  style_test.SetStatColor( 19 )
  style_test.SetStatFont( 62 )
  style_test.SetStatFontSize( 0 )
  style_test.SetStatFormat(const char* format = "6.4g")
  style_test.SetStatH( 0.1 )
  style_test.SetStatStyle( 1001 )
  style_test.SetStatTextColor( 1 )
  style_test.SetStatW( 0.19 )
  style_test.SetStatX( 0 )
  style_test.SetStatY( 0 )
  style_test.SetStripDecimals( kTRUE )
  style_test.SetTickLength(Float_t length = 0.03, Option_t* axis = "X")
  style_test.SetTimeOffset(Double_t toffset)
  style_test.SetTitleAlign( 13 )
  style_test.SetTitleBorderSize( 2 )
  style_test.SetTitleColor(Color_t color = 1, Option_t* axis = "X")
  style_test.SetTitleFillColor( 1 )
  style_test.SetTitleFont(Style_t font = 62, Option_t* axis = "X")
  style_test.SetTitleFontSize( 0 )
  style_test.SetTitleH( 0 )
  style_test.SetTitleOffset(Float_t offset = 1, Option_t* axis = "X")
  style_test.SetTitlePS(const char* pstitle)
  style_test.SetTitleSize(Float_t size = 0.02, Option_t* axis = "X")
  style_test.SetTitleStyle( 1001 )
  style_test.SetTitleTextColor( 1 )
  style_test.SetTitleW( 0 )
  style_test.SetTitleX( 0 )
  style_test.SetTitleXOffset( 1 )
  style_test.SetTitleXSize( 0.02 )
  style_test.SetTitleY( 0.985 )
  style_test.SetTitleYOffset( 1 )
  style_test.SetTitleYSize( 0.02 ) 
}
